[package]
name = "rradio"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = { version = "^1.4", features = ["fltk-bundled"] }
radiobrowser = "^0.6"
async-std = "1.12.0"
vlc-rs = "0.3.0"
json = "0.12.4"
serde_json = "1.0.127"